import fs from 'node:fs';

const I = (key,name,amount,unit,shoppingCategory,optional=false,rounding='none') => ({key,name,amount,unit,shoppingCategory,optional,rounding});
const V=(k,n,a,u='克',o=false,r='none')=>I(k,n,a,u,'蔬菜',o,r), M=(k,n,a,u='克',o=false,r='none')=>I(k,n,a,u,'肉蛋水产',o,r), S=(k,n,a,u='克',o=false,r='none')=>I(k,n,a,u,'调味品',o,r), O=(k,n,a,u='克',o=false,r='none')=>I(k,n,a,u,'其他',o,r);
const common={salt:S('salt','盐',3),oil:S('cooking-oil','食用油',20,'毫升'),soy:S('light-soy-sauce','生抽',10,'毫升'),ginger:V('ginger','姜',8),garlic:V('garlic','蒜',10)};
const specs = [
['tomato-egg','西红柿炒鸡蛋','vegetable','素菜',15,1,[V('tomato','西红柿',2,'个',false,'whole'),M('egg','鸡蛋',3,'枚',false,'ceil'),common.salt,common.oil,S('sugar','白糖',3,'克',true)],['西红柿洗净切块，鸡蛋加少许盐打散。','热锅放油，将鸡蛋炒至刚凝固后盛出。','原锅炒软西红柿，加入鸡蛋、盐和可选白糖，翻匀出锅。']],
['hot-sour-potato','酸辣土豆丝','vegetable','素菜',20,2,[V('potato','土豆',400),V('dried-chili','干辣椒',5),S('vinegar','香醋',15,'毫升'),common.salt,common.oil],['土豆切细丝，用清水淘洗掉表面淀粉并沥干。','热油煸香干辣椒，下土豆丝大火快速翻炒。','沿锅边淋醋，加盐炒至断生，保持爽脆后出锅。']],
['hand-torn-cabbage','手撕包菜','vegetable','素菜',15,1,[V('cabbage','包菜',500),common.garlic,V('dried-chili','干辣椒',4),common.soy,S('vinegar','香醋',8,'毫升'),common.oil],['包菜用手撕成小片，洗净后充分沥水。','热锅放油，爆香蒜和干辣椒。','下包菜大火炒软，加生抽和醋快速翻匀。']],
['garlic-broccoli','蒜蓉西兰花','vegetable','素菜',18,1,[V('broccoli','西兰花',450),V('garlic','蒜',20),common.salt,common.oil],['西兰花切小朵，用淡盐水浸泡后洗净。','沸水中加少许盐和油，焯西兰花约一分钟后捞出。','热油炒香蒜末，下西兰花和盐快速翻匀。']],
['braised-eggplant','红烧茄子','vegetable','素菜',30,2,[V('eggplant','茄子',500),V('green-pepper','青椒',80),common.garlic,common.soy,S('dark-soy-sauce','老抽',5,'毫升'),S('sugar','白糖',5),common.oil],['茄子切滚刀块，撒少许盐静置后挤去水分。','锅中放油，将茄子煎炒至软，加入青椒和蒜末。','加生抽、老抽、糖和少量水，烧至入味收汁。']],
['three-earthly-treasures','地三鲜','vegetable','素菜',30,3,[V('potato','土豆',250),V('eggplant','茄子',300),V('green-pepper','青椒',120),common.garlic,common.soy,S('starch','淀粉',5),common.oil],['土豆、茄子切滚刀块，青椒切片。','分别将土豆煎熟、茄子煎软，再下青椒略炒。','加入蒜末和生抽，用少量水淀粉勾薄芡后翻匀。']],
['oyster-lettuce','蚝油生菜','vegetable','素菜',12,1,[V('lettuce','生菜',400),common.garlic,S('oyster-sauce','蚝油',18,'毫升'),common.oil],['生菜逐片洗净并沥干，蒜切末。','沸水中加少许油，将生菜快速焯至变色后装盘。','热油炒香蒜末和蚝油，加少量水煮开后淋在生菜上。']],
['chive-egg','韭菜炒蛋','vegetable','素菜',12,1,[V('chive','韭菜',220),M('egg','鸡蛋',4,'枚',false,'ceil'),common.salt,common.oil],['韭菜洗净沥干切段，鸡蛋加盐打散。','热锅放油，把鸡蛋炒至蓬松后盛出。','下韭菜快速炒至断生，倒回鸡蛋翻匀。']],
['zucchini-egg','西葫芦炒鸡蛋','vegetable','素菜',15,1,[V('zucchini','西葫芦',400),M('egg','鸡蛋',3,'枚',false,'ceil'),common.salt,common.oil],['西葫芦洗净切薄片，鸡蛋加盐打散。','先将鸡蛋炒至凝固后盛出。','原锅炒西葫芦至断生，倒回鸡蛋加盐翻匀。']],
['scallion-tofu','葱煎豆腐','vegetable','素菜',22,2,[O('tofu','北豆腐',400),V('scallion','小葱',30),common.soy,common.oil],['豆腐切厚片，用厨房纸吸去表面水分。','平底锅放油，将豆腐两面煎至金黄。','淋入生抽和少量水，撒葱花焖一分钟。']],
['pepper-pork','辣椒炒肉','meat','肉菜',20,2,[M('pork-belly','五花肉',250),V('green-pepper','青椒',250),common.garlic,common.soy,S('doubanjiang','豆瓣酱',10),common.oil],['五花肉切薄片，青椒切滚刀块。','少油煸炒五花肉至出油微焦，加入蒜和豆瓣酱。','下青椒大火炒至起虎皮，加生抽翻匀。']],
['kung-pao-chicken','宫保鸡丁','meat','肉菜',30,3,[M('chicken-breast','鸡胸肉',350),O('peanut','花生米',60),V('dried-chili','干辣椒',8),V('scallion','大葱',50),common.soy,S('vinegar','香醋',12,'毫升'),S('sugar','白糖',10),S('starch','淀粉',10),common.oil],['鸡肉切丁，用生抽和淀粉腌十分钟。','调匀生抽、醋、糖和少量水，热油炒香辣椒和葱段。','下鸡丁炒熟，倒入料汁收浓，最后拌入花生米。']],
['fish-fragrant-pork','鱼香肉丝','meat','肉菜',30,3,[M('pork-tenderloin','猪里脊',300),V('wood-ear','泡发木耳',80),V('carrot','胡萝卜',100),V('green-pepper','青椒',100),S('pickled-chili','泡椒',20),common.soy,S('vinegar','香醋',15,'毫升'),S('sugar','白糖',12),S('starch','淀粉',10),common.oil],['里脊切丝，用生抽和淀粉腌制；配菜切丝。','将生抽、醋、糖、淀粉和水调成鱼香汁。','炒散肉丝后加入泡椒和配菜，倒入鱼香汁炒至浓稠。']],
['mapo-tofu','麻婆豆腐','meat','肉菜',25,3,[O('tofu','嫩豆腐',500),M('ground-pork','猪肉末',120),S('doubanjiang','豆瓣酱',25),S('sichuan-pepper','花椒粉',2),common.soy,S('starch','淀粉',8),common.oil],['豆腐切块，在淡盐水中焯一分钟后沥干。','热油炒散肉末，加入豆瓣酱炒出红油。','加水和豆腐烧入味，分次勾芡，撒花椒粉。']],
['cola-wings','可乐鸡翅','meat','肉菜',40,2,[M('chicken-wing','鸡翅中',10,'个',false,'ceil'),O('cola','可乐',330,'毫升'),common.ginger,common.soy,S('dark-soy-sauce','老抽',5,'毫升')],['鸡翅两面划刀，冷水下锅焯去浮沫。','煎至两面金黄，加入姜片、生抽、老抽和可乐。','煮开后转小火焖熟，最后大火收至汤汁浓亮。']],
['braised-chicken','黄焖鸡','meat','肉菜',50,3,[M('chicken-thigh','鸡腿',600),V('shiitake','香菇',150),V('potato','土豆',250),V('green-pepper','青椒',100),common.ginger,common.soy,S('dark-soy-sauce','老抽',8,'毫升'),common.oil],['鸡腿剁块焯水，香菇和土豆切块。','炒香姜片和鸡块，加生抽、老抽和热水。','加入香菇和土豆焖至软烂，最后下青椒收汁。']],
['potato-ribs','土豆炖排骨','stew','炖菜',65,3,[M('pork-ribs','排骨',600),V('potato','土豆',400),common.ginger,V('scallion','大葱',30),common.soy,S('dark-soy-sauce','老抽',8,'毫升'),common.oil],['排骨冷水下锅焯水，洗净浮沫；土豆切块。','炒香葱姜和排骨，加生抽、老抽及热水，小火炖四十分钟。','加入土豆继续炖至软烂，按口味加盐收汁。']],
['tomato-beef-stew','西红柿土豆炖牛肉','stew','炖菜',90,3,[M('beef-brisket','牛腩',600),V('tomato','西红柿',3,'个',false,'whole'),V('potato','土豆',350),V('onion','洋葱',120),common.ginger,common.salt],['牛腩切块冷水焯净，西红柿和土豆切块。','炒软洋葱和一半西红柿，加入牛腩与热水炖约一小时。','加入土豆和剩余西红柿，炖软后加盐调味。']],
['twice-cooked-pork','回锅肉','meat','肉菜',40,3,[M('pork-belly','五花肉',400),V('green-garlic','蒜苗',180),S('doubanjiang','豆瓣酱',20),S('sweet-bean-paste','甜面酱',8),common.ginger,common.oil],['五花肉与姜片煮至八成熟，放凉后切薄片。','少油煸炒肉片至卷曲出油，加入豆瓣酱和甜面酱。','下蒜苗大火翻炒至断生。']],
['mushroom-chicken','香菇滑鸡','meat','肉菜',35,2,[M('chicken-thigh','鸡腿肉',450),V('shiitake','香菇',180),common.ginger,common.soy,S('oyster-sauce','蚝油',12,'毫升'),S('starch','淀粉',8),common.oil],['鸡腿肉切块，用生抽、蚝油和淀粉腌十五分钟。','香菇切片，热油炒香姜丝和鸡肉。','鸡肉变色后下香菇，加少量水焖熟收汁。']],
['onion-pork','洋葱炒猪肉','meat','肉菜',20,2,[M('pork-tenderloin','猪里脊',280),V('onion','洋葱',300),common.soy,S('starch','淀粉',6),common.oil],['猪肉切片，用生抽和淀粉腌十分钟；洋葱切丝。','热锅滑炒肉片至变色后盛出。','原锅炒软洋葱，倒回肉片加盐翻匀。']],
['cabbage-pork-noodle-stew','白菜猪肉炖粉条','stew','炖菜',50,3,[M('pork-belly','五花肉',300),V('napa-cabbage','大白菜',600),O('glass-noodle','红薯粉条',150),common.ginger,common.soy,S('dark-soy-sauce','老抽',6,'毫升')],['粉条提前泡软，白菜切大片，五花肉切片。','煸香五花肉和姜片，加生抽、老抽及热水。','下白菜和粉条，中小火炖至粉条软透。']],
['eggplant-potato-stew','茄子炖土豆','mixed','混合菜',35,2,[V('eggplant','茄子',400),V('potato','土豆',350),V('green-pepper','青椒',80),common.garlic,common.soy,common.oil],['茄子和土豆切块，青椒切片。','热油将土豆煎至边缘金黄，下茄子炒软。','加生抽和热水焖至软烂，加入青椒和蒜末收汁。']],
['pepper-potato-pork','青椒土豆炒肉','mixed','混合菜',25,2,[M('pork-tenderloin','猪里脊',220),V('potato','土豆',280),V('green-pepper','青椒',160),common.soy,S('starch','淀粉',6),common.oil],['肉切片腌制，土豆和青椒切片。','先将肉片炒至变色盛出，再炒土豆片至断生。','加入青椒和肉片，淋生抽快速翻匀。']],
['garlic-sprout-mince','蒜苔炒肉末','mixed','混合菜',20,2,[M('ground-pork','猪肉末',250),V('garlic-sprout','蒜苔',350),common.soy,S('doubanjiang','豆瓣酱',8,true),common.oil],['蒜苔洗净切小段。','热油炒散肉末至微焦，可加入豆瓣酱炒香。','下蒜苔大火翻炒至断生，加生抽调味。']],
['tomato-egg-soup','西红柿鸡蛋汤','soup','汤',15,1,[V('tomato','西红柿',2,'个',false,'whole'),M('egg','鸡蛋',2,'枚',false,'ceil'),V('scallion','小葱',10),common.salt,S('sesame-oil','香油',3,'毫升',true)],['西红柿切块，鸡蛋打散。','锅中加水和西红柿煮至出味。','缓缓淋入蛋液，凝固后加盐，撒葱花和可选香油。']],
['seaweed-egg-soup','紫菜蛋花汤','soup','汤',10,1,[O('seaweed','干紫菜',10),M('egg','鸡蛋',2,'枚',false,'ceil'),V('scallion','小葱',10),common.salt,S('sesame-oil','香油',3,'毫升',true)],['紫菜撕小片，鸡蛋打散，葱切花。','水烧开后放入紫菜煮一分钟。','淋入蛋液，关火后加盐、葱花和可选香油。']],
['corn-rib-soup','玉米排骨汤','soup','汤',80,2,[M('pork-ribs','排骨',600),V('corn','甜玉米',2,'根',false,'whole'),V('carrot','胡萝卜',150),common.ginger,common.salt],['排骨冷水下锅焯净，玉米切段，胡萝卜切块。','排骨、姜片和足量清水煮开，转小火炖五十分钟。','加入玉米和胡萝卜再炖二十分钟，加盐调味。']],
['yam-corn-rib-soup','排骨山药玉米汤','soup','汤',90,2,[M('pork-ribs','排骨',600),V('yam','山药',350),V('corn','甜玉米',1,'根',false,'whole'),V('carrot','胡萝卜',120),common.ginger,common.salt],['排骨焯水，山药去皮切块，玉米切段。','排骨和姜片加水，小火炖约一小时。','放入玉米、山药和胡萝卜再炖二十五分钟，加盐。']],
['cucumber-century-egg-soup','黄瓜皮蛋汤','soup','汤',20,2,[V('cucumber','黄瓜',1,'根',false,'whole'),M('century-egg','皮蛋',2,'枚',false,'ceil'),V('scallion','小葱',10),common.ginger,common.salt,S('sesame-oil','香油',3,'毫升',true)],['黄瓜切片，皮蛋切小块，姜切丝。','少油煸香姜丝和皮蛋，加热水煮五分钟。','加入黄瓜片煮至断生，加盐和可选香油。']]
];
const excludedIds=new Set(['braised-eggplant','three-earthly-treasures','eggplant-potato-stew']);
const activeSpecs=specs.filter(([id])=>!excludedIds.has(id));
activeSpecs.push(
['stir-fried-bok-choy','清炒小白菜','vegetable','素菜',12,1,[V('bok-choy','小白菜',450),common.garlic,common.salt,common.oil],['小白菜洗净沥干，菜梗和菜叶分开放。','热油炒香蒜末，先下菜梗翻炒。','加入菜叶和盐，大火炒至刚软即可。']],
['garlic-a-choy','蒜蓉油麦菜','vegetable','素菜',10,1,[V('a-choy','油麦菜',450),V('garlic','蒜',20),common.salt,common.oil],['油麦菜洗净切段，蒜切末。','热锅放油，小火炒香蒜末。','下油麦菜大火翻炒，断生后加盐。']],
['mushroom-bok-choy','香菇油菜','vegetable','素菜',18,1,[V('bok-choy','油菜',400),V('shiitake','香菇',180),S('oyster-sauce','蚝油',15,'毫升'),common.garlic,common.oil],['油菜和香菇分别洗净，香菇切片。','油菜焯水后摆盘，热油炒香蒜末和香菇。','加入蚝油和少量水烧浓，浇在油菜上。']],
['celery-pork','芹菜炒肉','mixed','混合菜',20,2,[M('pork-tenderloin','猪里脊',250),V('celery','芹菜',300),common.soy,S('starch','淀粉',6),common.oil],['猪肉切丝，用生抽和淀粉腌十分钟；芹菜切段。','热锅滑炒肉丝至变色后盛出。','下芹菜炒至断生，倒回肉丝翻匀。']],
['moo-shu-pork','木须肉','mixed','混合菜',25,2,[M('pork-tenderloin','猪里脊',200),M('egg','鸡蛋',3,'枚',false,'ceil'),V('wood-ear','泡发木耳',100),V('cucumber','黄瓜',150),common.soy,common.oil],['肉切片，鸡蛋打散，木耳和黄瓜切片。','鸡蛋炒熟盛出，再将肉片炒至变色。','加入木耳和黄瓜，倒回鸡蛋加生抽翻匀。']],
['carrot-pork','胡萝卜炒肉','mixed','混合菜',20,1,[M('pork-tenderloin','猪里脊',240),V('carrot','胡萝卜',280),common.soy,S('starch','淀粉',6),common.oil],['猪肉切片腌制，胡萝卜切薄片。','热油炒肉片至变色后盛出。','炒软胡萝卜，倒回肉片加生抽翻匀。']],
['lettuce-stem-pork','莴笋炒肉','mixed','混合菜',20,2,[M('pork-tenderloin','猪里脊',240),V('lettuce-stem','莴笋',350),common.garlic,common.soy,S('starch','淀粉',6),common.oil],['莴笋去皮切片，猪肉切片腌制。','热油炒肉片至变色后盛出。','炒香蒜末和莴笋，倒回肉片翻匀。']],
['pan-fried-chicken-thigh','香煎鸡腿','meat','肉菜',35,2,[M('chicken-thigh','去骨鸡腿',500),common.ginger,common.soy,S('oyster-sauce','蚝油',12,'毫升'),common.oil],['鸡腿肉擦干，用生抽、蚝油和姜腌十五分钟。','平底锅少油，鸡皮朝下中小火煎至金黄。','翻面煎熟，静置两分钟后切块。']],
['potato-chicken','土豆烧鸡','stew','炖菜',50,2,[M('chicken-thigh','鸡腿',600),V('potato','土豆',400),common.ginger,common.soy,S('dark-soy-sauce','老抽',6,'毫升'),common.oil],['鸡腿剁块焯水，土豆切块。','炒香姜片和鸡块，加生抽、老抽及热水炖二十分钟。','加入土豆继续炖至软烂，收汁出锅。']],
['red-braised-pork','红烧肉','meat','肉菜',75,3,[M('pork-belly','五花肉',600),common.ginger,common.soy,S('dark-soy-sauce','老抽',10,'毫升'),S('rock-sugar','冰糖',25),O('star-anise','八角',2,'个')],['五花肉切块焯水，沥干备用。','小火融化冰糖，放肉块炒至上色，加姜、八角和酱油。','加热水没过肉，小火焖至软糯后收汁。']],
['sweet-sour-ribs','糖醋排骨','meat','肉菜',55,3,[M('pork-ribs','排骨',600),common.ginger,common.soy,S('vinegar','香醋',25,'毫升'),S('sugar','白糖',25),common.oil],['排骨焯水后沥干，少油煎至表面金黄。','加入姜、生抽、醋、糖和热水。','小火焖熟，最后大火收成浓亮糖醋汁。']],
['steamed-egg','蒸水蛋','vegetable','素菜',18,1,[M('egg','鸡蛋',3,'枚',false,'ceil'),S('light-soy-sauce','生抽',5,'毫升'),S('sesame-oil','香油',3,'毫升',true),V('scallion','小葱',8)],['鸡蛋打散，加入约 1.5 倍温水搅匀并过滤。','盖住碗口，水开后中小火蒸约十分钟。','关火焖两分钟，淋生抽和可选香油，撒葱花。']],
['home-style-tofu','家常豆腐','mixed','混合菜',25,2,[O('tofu','北豆腐',450),V('wood-ear','泡发木耳',80),V('carrot','胡萝卜',100),common.garlic,common.soy,S('oyster-sauce','蚝油',12,'毫升'),common.oil],['豆腐切片煎至两面金黄，木耳和胡萝卜切片。','炒香蒜末，加入木耳和胡萝卜翻炒。','放回豆腐，加生抽、蚝油和少量水焖入味。']],
['cucumber-egg','黄瓜炒蛋','vegetable','素菜',12,1,[V('cucumber','黄瓜',300),M('egg','鸡蛋',3,'枚',false,'ceil'),common.salt,common.oil],['黄瓜切片，鸡蛋加盐打散。','热油将鸡蛋炒至凝固后盛出。','下黄瓜快速翻炒，倒回鸡蛋加盐炒匀。']],
['cabbage-vermicelli','包菜炒粉丝','vegetable','素菜',22,2,[V('cabbage','包菜',350),O('glass-noodle','粉丝',120),M('egg','鸡蛋',2,'枚',false,'ceil'),common.soy,common.oil],['粉丝泡软剪短，包菜切丝，鸡蛋炒熟盛出。','热油下包菜炒软，加入粉丝。','淋生抽翻炒均匀，最后倒回鸡蛋。']],
['soy-glazed-drumsticks','酱香鸡腿','meat','肉菜',45,2,[M('chicken-drumstick','鸡小腿',8,'个',false,'ceil'),common.ginger,common.soy,S('dark-soy-sauce','老抽',8,'毫升'),S('sugar','白糖',8)],['鸡腿划刀后焯水，洗净浮沫。','加入姜、生抽、老抽、糖和热水煮开。','转小火焖至熟透，最后大火收汁。']],
['winter-melon-shrimp-skin','虾皮烧冬瓜','vegetable','素菜',20,1,[V('winter-melon','冬瓜',500),M('dried-shrimp','虾皮',20),V('scallion','小葱',10),common.salt,common.oil],['冬瓜去皮切片，虾皮用清水冲洗。','热油炒香虾皮，加入冬瓜翻炒。','加少量水焖至冬瓜透明，加盐和葱花。']]
);
const finalSpecs=activeSpecs.filter(([id])=>!new Set(['carrot-pork','lettuce-stem-pork','soy-glazed-drumsticks','winter-melon-shrimp-skin']).has(id));
const tagsByCategory={vegetable:['家常','清爽'],meat:['家常','下饭'],mixed:['家常','荤素搭配'],stew:['家常','暖胃'],soup:['家常','汤羹']};
const avoidTags=(ingredients,sourceCategory)=>{const keys=new Set(ingredients.map(x=>x.key));const avoid=[];if(keys.has('green-pepper'))avoid.push('pepper');if(sourceCategory==='aquatic'||[...keys].some(k=>k.includes('fish')))avoid.push('fish');if([...keys].some(k=>k.startsWith('pork')||k==='ground-pork'))avoid.push('pork');if(keys.has('egg')||keys.has('century-egg'))avoid.push('egg');if([...keys].some(k=>['dried-chili','pickled-chili','doubanjiang','sichuan-pepper'].includes(k)))avoid.push('spicy');return avoid};
const dishes=finalSpecs.map(([id,name,category,categoryName,durationMinutes,difficulty,ingredients,steps],i)=>{const sourceCategory=category==='soup'?'soup':category==='meat'?'meat_dish':'vegetable_dish';return {id,name,sourceCategory,category,categoryName,tags:[...tagsByCategory[category],durationMinutes<=20?'快手':'耐心制作'],avoid:avoidTags(ingredients,sourceCategory),servings:2,durationMinutes,difficulty,homestyleScore:98-Math.floor(i*.8),homestyleRank:i+1,homestyleReason:'原料常见，步骤简单，适合家庭厨房和日常晚餐。',excludedFromApp:false,exclusionReason:null,image:null,ingredients,tools:['炒锅或汤锅','菜刀','砧板'],steps,notes:['食材用量为 2 人份参考值，调味请按口味调整。'],source:{project:'Anduin2017/HowToCook',path:`dishes/${sourceCategory}/${name}.md`,url:`https://github.com/Anduin2017/HowToCook/search?q=${encodeURIComponent(name)}`,license:'Unlicense',commit:null,retrievedAt:'2026-07-21'}}});
const index=dishes.map(({id,name,category,tags,avoid,homestyleScore,homestyleRank,durationMinutes})=>({id,name,category,categoryName:dishes.find(d=>d.id===id).categoryName,tags,avoid,homestyleScore,homestyleRank,durationMinutes,enabled:true}));
fs.writeFileSync(new URL('../data/dishes.json',import.meta.url),JSON.stringify({schemaVersion:1,updatedAt:'2026-07-21',dishes},null,2)+'\n');
fs.writeFileSync(new URL('../data/dish-index.json',import.meta.url),JSON.stringify(index,null,2)+'\n');
